import fs from 'node:fs';
import path from 'node:path';
import { ROOT, read, write } from './core.mjs';

export function generatedFiles(root = ROOT) {
  const files = {};
  for (const name of fs.readdirSync(path.join(root, 'harness', 'skills'))) {
    const source = read(path.join(root, 'harness', 'skills', name, 'SKILL.md'));
    const front = source.match(/^---\n[\s\S]*?\n---/)[0];
    for (const provider of ['.agents', '.claude']) files[`${provider}/skills/${name}/SKILL.md`] = `${front}\n\n<!-- Generated by node harness/sync.mjs; edit harness/skills/${name}/SKILL.md. -->\nRead [the shared ${name} workflow](../../../harness/skills/${name}/SKILL.md) and follow it.\nPaths inside that workflow are relative to the harness root. Preserve arguments supplied\nwith the skill invocation or in the conversation.\n`;
  }
  files['AGENTS.md'] = '# Research harness — Codex\n\nRead [harness/PROTOCOL.md](harness/PROTOCOL.md) before working in this repository.\nIt is the shared research policy for Codex and Claude on macOS and Windows.\nUse the available tools for the requested operation; tool names in examples are not dependencies.\nProject hooks are in `.codex/hooks.json`. If they are not trusted or did not run, use\nthe explicit checkpoint commands in the protocol and report the outcome.\n';
  files['CLAUDE.md'] = '# Research harness — Claude Code\n\n@harness/PROTOCOL.md\n\nThe imported file is the shared research policy for Claude and Codex on macOS and Windows.\nProject hooks are in `.claude/settings.json`. If hooks did not run, use the explicit\ncheckpoint commands in the protocol and report the outcome.\n';
  return files;
}
export function sync(root = ROOT, check = false) {
  const differences = [];
  for (const [name, content] of Object.entries(generatedFiles(root))) {
    const file = path.join(root, name);
    if (!fs.existsSync(file) || read(file).replace(/\r\n/g, '\n') !== content) {
      differences.push(name);
      if (!check) write(file, content);
    }
  }
  return differences;
}
if (process.argv[1]?.endsWith('sync.mjs')) {
  const check = process.argv.includes('--check');
  const differences = sync(ROOT, check);
  console.log(JSON.stringify({ check, differences }));
  if (check && differences.length) process.exitCode = 1;
}
